backend:
  name: github
  repo: hyperboi6898/hyperliquidvn # Replace with your GitHub repo
  branch: main # Or your default branch
  site_domain: hyperliquidvietnam.xyz # Replace with your actual domain
  base_url: https://sveltia-cms-auth.hyperboi6898.workers.dev

media_folder: "public/uploads" # Where to store uploaded images
public_folder: "/uploads" # The src attribute for uploaded assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog" # Or src/content/blog, depending on where Contentlayer will look
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "news"
    label: "News"
    folder: "content/news" # Or src/content/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "news" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Source URL", name: "source_url", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
